/** Nombres de las texturas, animaciones y sonidos de Phaser, calculados siempre igual desde el manifest. */
export const K = {
  ui: (n: string) => `ui_${n}`,
  pers: (id: string, anim: string) => `p_${id}_${anim}`,
  retrato: (id: string) => `retrato_${id}`,
  fx: (n: string) => `fx_${n}`,
  obj: (n: string, anim: string) => `o_${n}_${anim}`,
  cri: (n: string, anim: string) => `c_${n}_${anim}`,
  par: (n: string) => `par_${n}`,
  aud: (n: string) => `a_${n}`,
  atlas: (n: string, tam: '32' | '64') => `atlas_${n}_${tam}`,
  anim: (id: string, anim: string, dir: string) => `${id}_${anim}_${dir}`,
  animFx: (n: string) => `afx_${n}`,
  suelo: (i: number) => `suelo_${i}`,
  agua: 'agua',
  luz: 'luz',
  nube: 'nube',
  nieblaNubes: 'niebla_nubes',
  nieblaJirones: 'niebla_jirones',
  mapa: 'mapa_tiled',
  manifest: 'manifest',
  catalogo: 'catalogo',
  postal: (n: string) => `postal_${n}`,
} as const
